services:
  vpn:
    container_name: vpn
    image: ghcr.io/bubuntux/nordlynx:latest
    profiles: ["${PROFILE_VPN:-network}"]
    restart: unless-stopped
    networks:
      - external
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    cap_add:
      - "NET_ADMIN"
      - "NET_RAW"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1 # ipv4 only
    ports:
      - "1080:1080" # Allow proxy connections from outside docker
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
      # Image
      PRIVATE_KEY: "${NORDLYNX_PRIVATE_KEY:?You must set the NordLynx private key to use this}"
      CONNECT: "United_States"
      DNS: "1.1.1.1,8.8.8.8"
      NET_LOCAL: "192.168.0.0/24"
      PRE_UP: "sleep 3" # Delay startup to prevent race conditions
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "deunhealth.restart.on.unhealthy=true"
      - "traefik.enable=false"
