services:
  vpn:
    container_name: vpn
    image: ${VPN_IMAGE:-qmcgaw/gluetun}:${VPN_IMAGE_TAG:-latest}
    profiles: ["${VPN_PROFILE:-network}"]
    restart: unless-stopped
    networks:
      - external
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    cap_add:
      - "NET_ADMIN"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - "1080:1080" # Allow Socks5 proxy connections from outside docker
      - "8888:8888" # Allow HTTP proxy connections from outside docker

      - "8000:8000"
    environment:
      # Default
      TZ: "${TZ:-Europe/London}"
      PUID: "$PUID"
      PGID: "$PGID"
      # Image
      VPN_SERVICE_PROVIDER: "${VPN_SERVICE_PROVIDER}"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${VPN_WIREGUARD_PRIVATE_KEY}"

      SERVER_COUNTRIES: "${VPN_SERVER_COUNTRIES:-United States}"
      SERVER_REGIONS: "${VPN_SERVER_REGIONS}"
      SERVER_CITIES: "${VPN_SERVER_CITIES}"
      SERVER_HOSTNAMES: "${VPN_SERVER_HOSTNAMES}"
      SERVER_CATEGORIES: "${VPN_SERVER_CATEGORIES}"

      HTTPPROXY: "on"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/dev/net/tun:/dev/net/tun"
      - "./config.toml:/gluetun/auth/config.toml:ro"
    labels:
      - "deunhealth.restart.on.unhealthy=false" # This can be unhealthy but still be connected

      - "homepage.group=Information"
      - "homepage.name=VPN"
      - "homepage.icon=gluetun.png"
      - "homepage.description=Gluetun | HTTP - vpn:8888 | Socks5 - vpn:1080"
      - "homepage.widget.type=gluetun"
      - "homepage.widget.url=http://vpn:8000"

      - "traefik.enable=false"

  proxy:
    container_name: proxy
    image: ${PROXY_IMAGE:-serjs/go-socks5-proxy}:${PROXY_IMAGE_TAG:-latest}
    profiles: ["${PROXY_PROFILE:-network}"]
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      vpn:
        condition: service_healthy
        restart: true
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      PROXY_USER: "${PROXY_USER:-}"
      PROXY_PASSWORD: "${PROXY_PASSWORD:-}"
    labels:
      - "deunhealth.restart.on.unhealthy=false"
      - "traefik.enable=false"
