services:
  openspeedtest:
    container_name: openspeedtest
    image: openspeedtest/latest
    profiles: ["${PROFILE_OPENSPEEDTEST:-network}"]
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      DOMAIN_NAME: "openspeedtest.$DOMAIN"
      HTTP_PORT: "3000"
      SET_USER: "$PUID"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Information"
      - "homepage.name=OpenSpeedTest"
      - "homepage.icon=openspeedtest.png"
      - "homepage.href=https://openspeedtest.$DOMAIN/"
      - "homepage.description=Bandwidth test to server"

      - "traefik.enable=true"
      - "traefik.http.routers.openspeedtest.rule=Host(`openspeedtest.$DOMAIN`)"
      - "traefik.http.routers.openspeedtest.middlewares=openspeedtest,tinyauth,error-pages"
      - "traefik.http.services.openspeedtest.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.openspeedtest.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.openspeedtest.headers.accessControlAllowOriginList=https://$DOMAIN"

    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "curl --connect-timeout 15 --silent --show-error --fail http://localhost:3000/"
