services:
  qbittorrent:
    container_name: qbittorrent
    image: ${QBITTORRENT_IMAGE:-lscr.io/linuxserver/qbittorrent}:${QBITTORRENT_IMAGE_TAG:-latest}
    profiles: ["${QBITTORRENT_PROFILE:-download}"]
    extends:
      file: ../compose.extend.yaml
      service: "vpn-${USE_VPN:-false}"
    restart: unless-stopped
    networks:
      - external
      - internal
    ports:
      - "51414:51414"
    depends_on:
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./logs:/config/qBittorrent/logs"
      - "$PATH_DOWNLOADS:/data/Downloads"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Download"
      - "homepage.name=qBittorrent"
      - "homepage.icon=qbittorrent.png"
      - "homepage.href=https://qbittorrent.$DOMAIN/"
      - "homepage.description=Torrents"
      - "homepage.weight=50"
      - "homepage.widget.type=qbittorrent"
      - "homepage.widget.url=http://qbittorrent:8080"

      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.$DOMAIN`)"
      - "traefik.http.routers.qbittorrent.middlewares=qbittorrent,tinyauth,error-pages"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.qbittorrent.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.qbittorrent.headers.accessControlAllowOriginList=https://$DOMAIN"

    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "curl --connect-timeout 15 --silent --show-error --fail http://localhost:8080/"
