services:
  whisparr:
    container_name: whisparr
    image: ${WHISPARR_IMAGE:-ghcr.io/hotio/whisparr}:${WHISPARR_IMAGE_TAG:-latest}
    profiles: ["${WHISPARR_PROFILE:-media}"]
    extends:
      file: ../compose.extend.yaml
      service: "pg-${USE_POSTGRES:-false}_vpn-${USE_VPN:-false}"
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "${TZ:-Europe/London}"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./backup:/config/Backups"
      - "./logs:/config/logs"
      - "$PATH_ADULT:/data/adult"
      - "$PATH_DOWNLOADS:/data/Downloads"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Media"
      - "homepage.name=Whisparr"
      - "homepage.icon=whisparr.png"
      - "homepage.href=https://whisparr.$DOMAIN/"
      - "homepage.description=Porn"
      - "homepage.widget.type=sonarr"
      - "homepage.widget.url=http://whisparr:6969"
      - "homepage.widget.key=${WHISPARR_API:-}"

      - "traefik.enable=true"
      - "traefik.http.routers.whisparr.rule=Host(`whisparr.$DOMAIN`)"
      - "traefik.http.routers.whisparr.middlewares=whisparr,tinyauth,error-pages"
      - "traefik.http.services.whisparr.loadbalancer.server.port=6969"
      - "traefik.http.middlewares.whisparr.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.whisparr.headers.accessControlAllowOriginList=https://$DOMAIN"

    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "curl --connect-timeout 15 --silent --show-error --fail http://localhost:6969/"
