services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:latest # v3
    profiles: ["${PROFILE_WHISPARR:-media}"]
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      proxy:
        condition: service_started
        restart: false
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./backup:/config/Backups"
      - "./logs:/config/logs"
      - "$PATH_ADULT:/data/adult"
      - "$PATH_DOWNLOADS:/data/Downloads"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.whisparr.rule=Host(`whisparr.$DOMAIN`)"
      - "traefik.http.routers.whisparr.middlewares=whisparr,oauth,error-pages"
      - "traefik.http.services.whisparr.loadbalancer.server.port=6969"
      - "traefik.http.middlewares.whisparr.headers.accessControlAllowOriginList=*"
    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "curl --connect-timeout 15 --silent --show-error --fail http://localhost:6969/"
