services:
  overseerr:
    container_name: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    profiles: ["${PROFILE_OVERSEERR:-information}"]
    restart: unless-stopped
    networks:
      - external
      - internal
    depends_on:
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
      # Image
      LOG_LEVEL: "debug"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./logs:/config/logs"
      - "./tmp:/run/overseerr-temp"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.$DOMAIN`) || Host(`ask.$DOMAIN`)"
      - "traefik.http.routers.overseerr.middlewares=overseerr,error-pages"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
      - "traefik.http.middlewares.overseerr.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.overseerr.headers.accessControlAllowOriginList=https://$DOMAIN"
    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "curl --connect-timeout 5 --silent --show-error --fail http://localhost:5055/"
