services:
  foundryvtt:
    environment:
      AUTO_PROVISION: "true"
      CONTAINER_PATCH_URLS: "https://github.com/MaienM/foundry-vtt-header-auth/releases/download/${FOUNDRYVTT_HEADER_AUTH_VERSION:-v14.360.1}/patches.sh"
      HEADER_USERNAME: "remote-user"
      HEADER_ROLES: "remote-groups"
      ROLE_ADMIN: "${FOUNDRYVTT_ROLE_ADMIN:-foundry_dm}"
      ROLE_PLAYER: "${FOUNDRYVTT_ROLE_PLAYER:-foundry_player}"
    labels:
      tinyauth.apps.foundryvtt.oauth.groups: "${FOUNDRYVTT_ROLE_ADMIN:-dm},${FOUNDRYVTT_ROLE_PLAYER:-player}"
      traefik.http.routers.foundryvtt.middlewares: "tinyauth,error-pages"
