# All default services to get the stack running. Create a file called
# `compose.override.yaml` from the template to add more.

name: rycochet

include:
  - cloudflared/compose.yaml #    | Cloudflare tunnel |
  - deunhealth/compose.yaml #     | Bring unhealthy containers back up |
  - error-pages/compose.yaml #    | Error pages |
  - socket-proxy/compose.yaml #   | Secure access to the docker socket |
  - tinyauth/compose.yaml #       | OAuth via Google |
  - traefik/compose.yaml #        | HTTP routing |
  - vpn/compose.yaml #            | VPN + HTTP Proxy + Socks5 Proxy |
  - watchtower/compose.yaml #     | Auto-update containers |

networks:
  external:
    name: "external"
    driver: bridge
    driver_opts:
      # Prevent services using this from talking to each other
      com.docker.network.bridge.enable_icc: "false"
    enable_ipv4: true
    enable_ipv6: true

  internal:
    # No internet access
    name: "internal"
    driver: bridge
    internal: true
    enable_ipv4: true
    enable_ipv6: false
