services:
  papermc:
    container_name: papermc
    image: marctv/minecraft-papermc-server:latest
    profiles: ["${PROFILE_PAPERMC:-games}"]
    restart: unless-stopped
    ports:
      - "25565:25565/tcp"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      # Image
      MEMORYSIZE: "1G"
    depends_on:
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/data"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.enable=true"
      - "traefik.http.routers.papermc.rule=Host(`minecraft-map.$DOMAIN`)"
      - "traefik.http.routers.papermc.middlewares=error-pages"
      - "traefik.http.services.papermc.loadbalancer.server.port=8080"
    healthcheck:
      interval: "30s"
      timeout: "1s"
      retries: 3
      start_period: "5m"
      test: "timeout 1 bash -c 'cat < /dev/null > /dev/tcp/localhost/25565'"
