services:
  webtop:
    container_name: webtop
    image: lscr.io/linuxserver/webtop:latest
    profiles: ["${PROFILE_WEBTOP:-desktop}"]
    restart: unless-stopped
    networks:
      - external
      - internal
    depends_on:
      proxy:
        condition: service_started
        restart: false
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    # security_opt:
    #   - seccomp:unconfined #optional
    shm_size: "1gb"
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
      # Image
      TITLE: "Webtop"
      PASSWORD: ""
      NO_DECOR: true
      # Auto-install LSIO mods and packages
      DOCKER_MODS: "linuxserver/mods:universal-package-install"
      INSTALL_PACKAGES: "mkvtoolnix|bento4"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "$PATH_DOWNLOADS:/data/Downloads"
      - "$PATH_MOVIES:/data/movies:ro"
      - "$PATH_TV:/data/tv:ro"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.enable=true"
      - "traefik.http.routers.webtop.rule=Host(`webtop.$DOMAIN`)"
      - "traefik.http.routers.webtop.middlewares=webtop,tinyauth,error-pages"
      - "traefik.http.services.webtop.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.webtop.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.webtop.headers.accessControlAllowOriginList=https://$DOMAIN"
    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "curl --connect-timeout 5 --silent --show-error --fail http://localhost:3000/"
