services:
  readarr:
    container_name: readarr
    image: ${READARR_IMAGE:-lscr.io/linuxserver/readarr}:${READARR_IMAGE_TAG:-0.4.18-develop}
    profiles: ["${READARR_PROFILE:-media}"]
    extends:
      file: ../compose.extend.yaml
      service: "pg-${USE_POSTGRES:-false}_vpn-${USE_VPN:-false}"
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./backup:/config/Backups"
      - "./logs:/config/logs"
      - "$PATH_AUDIOBOOKS:/data/Audiobooks"
      - "$PATH_BOOKS:/data/Books"
      - "$PATH_DOWNLOADS:/data/Downloads"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Media"
      - "homepage.name=Readarr"
      - "homepage.icon=readarr.png"
      - "homepage.href=readarr://readarr.$DOMAIN/"
      - "homepage.description=Audiobooks and Ebooks"
      - "homepage.widget.type=readarr"
      - "homepage.widget.url=http://readarr:8787"
      - "homepage.widget.key=${READARR_API:-}"

      - "traefik.enable=true"
      - "traefik.http.routers.readarr.rule=Host(`readarr.$DOMAIN`)"
      - "traefik.http.routers.readarr.middlewares=readarr,tinyauth,error-pages"
      - "traefik.http.services.readarr.loadbalancer.server.port=8787"
      - "traefik.http.middlewares.readarr.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.readarr.headers.accessControlAllowOriginList=https://$DOMAIN"

    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "curl --connect-timeout 15 --silent --show-error --fail http://localhost:8787/"
