services:
  prowlarr:
    container_name: prowlarr
    image: ${PROWLARR_IMAGE:-lscr.io/linuxserver/prowlarr}:${PROWLARR_IMAGE_TAG:-latest}
    profiles: ["${PROWLARR_PROFILE:-download}"]
    extends:
      file: ../compose.extend.yaml
      service: "vpn-${USE_VPN:-false}"
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./backup:/config/Backups"
      - "./logs:/config/logs"
      - "$PATH_DOWNLOADS:/data/Downloads"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Download"
      - "homepage.name=Prowlarr"
      - "homepage.icon=prowlarr.png"
      - "homepage.href=https://prowlarr.$DOMAIN/"
      - "homepage.description=Search"
      - "homepage.widget.type=prowlarr"
      - "homepage.widget.url=http://prowlarr:9696"
      - "homepage.widget.key=${PROWLARR_API:-}"

      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.$DOMAIN`)"
      - "traefik.http.routers.prowlarr.middlewares=prowlarr,tinyauth,error-pages"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "traefik.http.middlewares.prowlarr.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.prowlarr.headers.accessControlAllowOriginList=https://$DOMAIN"

    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "curl --connect-timeout 15 --silent --show-error --fail http://localhost:9696/"
