services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop
    profiles: ["download"]
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      vpn:
        condition: service_started
        restart: true
      traefik:
        condition: service_started
      error-pages:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./backup:/config/Backups"
      - "./logs:/config/logs"
      - "$PATH_DOWNLOADS:/data/Downloads"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.$DOMAIN`)"
      - "traefik.http.routers.prowlarr.middlewares=oauth,error-pages"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "curl --connect-timeout 15 --silent --show-error --fail http://localhost:9696/"
