services:
  plex:
    container_name: plex
    image: ${PLEX_IMAGE:-plexinc/pms-docker}:${PLEX_IMAGE_TAG:-latest}
    profiles: ["${PLEX_PROFILE:-library}"]
    extends:
      file: ../compose.extend.yaml
      service: "cf-${USE_CLOUDFLARED:-true}_gpu-${USE_GPU:-none}"
    restart: unless-stopped
    networks:
      - external
      - internal
    depends_on:
      traefik:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    ports:
      - "32400:32400"
    environment:
      # Default
      TZ: "${TZ:-Europe/London}"
      # Image
      ADVERTISE_IP: "https://plex.$DOMAIN:443/"
      PLEX_CLAIM: "$PLEX_CLAIM"
      PLEX_GID: "$PGID"
      PLEX_UID: "$PUID"
    volumes:
      - "./config:/config"
      - "./backup:/data/backup" # TODO: Fix this - /config/Library/Application Support/Plex Media Server/Plug-in Support/Databases ...?
      - "./logs:/config/Library/Application Support/Plex Media Server/Logs"
      - "./tmp:/tmp"
      - "$PATH_MOVIES:/data/movies:ro"
      - "$PATH_MUSIC:/data/Music:ro"
      - "$PATH_TV:/data/tv:ro"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Libraries"
      - "homepage.name=Plex"
      - "homepage.icon=plex.png"
      - "homepage.href=https://plex.$DOMAIN/web/index.html"
      - "homepage.weight=-1"
      - "homepage.description=Media Library"
      - "homepage.widgets[0].type=plex"
      - "homepage.widgets[0].url=https://plex:32400"
      - "homepage.widgets[0].key=${PLEX_TOKEN:-}"
      - "homepage.widgets[1].type=tautulli"
      - "homepage.widgets[1].url=http://tautulli:8181"
      - "homepage.widgets[1].key=${TAUTULLI_API:-}"
      - "homepage.widgets[1].showEpisodeNumber=true"
      - "homepage.widgets[1].expandOneStreamToTwoRows=false"

      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.$DOMAIN`)"
      - "traefik.http.routers.plex.middlewares=plex,error-pages"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.services.plex.loadbalancer.server.scheme=https"
      - "traefik.http.middlewares.plex.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.plex.headers.accessControlAllowOriginList=https://$DOMAIN"
      # - "traefik.http.middlewares.plex.redirectregex.regex=^https?://plex.$DOMAIN/$"
      # - "traefik.http.middlewares.plex.redirectregex.replacement=https://plex.$DOMAIN/web/index.html"

    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "curl --connect-timeout 15 --silent --show-error --fail http://localhost:32400/identity"
