services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    profiles: ["${PROFILE_PLEX:-library}"]
    restart: unless-stopped
    networks:
      - external
      - internal
    depends_on:
      cloudflared:
        condition: service_started
        restart: false
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "4"
        # reservations:
        #   devices:
        #     - driver: nvidia
        #       count: all
        #       capabilities: [gpu]
    ports:
      - "32400:32400"
    environment:
      # Default
      TZ: "Europe/London"
      # GPU
      # NVIDIA_DRIVER_CAPABILITIES: "compute,video,utility"
      # NVIDIA_VISIBLE_DEVICES: "all"
      # Image
      ADVERTISE_IP: "https://plex.$DOMAIN:443/"
      PLEX_CLAIM: "$PLEX_CLAIM"
      PLEX_GID: "$PGID"
      PLEX_UID: "$PUID"
    volumes:
      - "./config:/config"
      - "./backup:/data/backup" # TODO: Fix this - /config/Library/Application Support/Plex Media Server/Plug-in Support/Databases ...?
      - "./logs:/config/Library/Application Support/Plex Media Server/Logs"
      - "./tmp:/tmp"
      - "$PATH_MOVIES:/data/movies:ro"
      - "$PATH_MUSIC:/data/Music:ro"
      - "$PATH_TV:/data/tv:ro"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.$DOMAIN`)"
      - "traefik.http.routers.plex.middlewares=plex,error-pages"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.services.plex.loadbalancer.server.scheme=https"
      - "traefik.http.middlewares.plex.replacepathregex.regex=^/$"
      - "traefik.http.middlewares.plex.replacepathregex.replacement=/web/index.html"
    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "curl --connect-timeout 15 --silent --show-error --fail http://localhost:32400/identity"
