services:
  komga:
    container_name: komga
    image: gotson/komga:latest
    profiles: ["media"]
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      vpn:
        condition: service_started
        restart: true
      traefik:
        condition: service_started
      error-pages:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
      # Image
      KOMGA_LIBRARIES_SCAN_CRON: "0 0 0 * * 0"
    user: "$PUID:$PGID"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./logs:/config/logs"
      - "$PATH_COMICS:/data/Comics"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.enable=true"
      - "traefik.http.routers.komga.rule=Host(`comics.$DOMAIN`)"
      - "traefik.http.routers.komga.middlewares=oauth,error-pages"
      - "traefik.http.services.komga.loadbalancer.server.port=25600"
    # healthcheck:
    #   interval: "30s"
    #   timeout: "5s"
    #   retries: 3
    #   start_period: "10s"
    #   test: "curl --connect-timeout 15 --silent --show-error --fail http://localhost:25600/"
