services:
  komga:
    container_name: komga
    image: ${KOMGA_IMAGE:-gotson/komga}:${KOMGA_IMAGE_TAG:-latest}
    profiles: ["${KOMGA_PROFILE:-library}"]
    restart: unless-stopped
    networks:
      - external
      - internal
    depends_on:
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "${TZ:-Europe/London}"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
      # Image
      KOMGA_LIBRARIES_SCAN_CRON: "0 0 0 * * 0"
    user: "$PUID:$PGID"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./logs:/config/logs"
      - "$PATH_COMICS:/data/Comics"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Libraries"
      - "homepage.name=Komga"
      - "homepage.icon=komga.png"
      - "homepage.href=readarr://komga.$DOMAIN/"
      - "homepage.description=Comics"
      - "homepage.widget.type=readarr"
      - "homepage.widget.url=http://komga:25600"
      - "homepage.widget.key=${KOMGA_API:-}"

      - "traefik.enable=true"
      - "traefik.http.routers.komga.rule=Host(`komga.$DOMAIN`)"
      - "traefik.http.routers.komga.middlewares=komga,tinyauth,error-pages"
      - "traefik.http.services.komga.loadbalancer.server.port=25600"
      - "traefik.http.middlewares.komga.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.komga.headers.accessControlAllowOriginList=https://$DOMAIN"

    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "curl --connect-timeout 5 --silent --show-error --fail http://localhost:25600/"
