services:
  pocket-id:
    depends_on:
      postfix:
        condition: service_started
        restart: false
    environment:
      SMTP_HOST: "postfix.internal"
      SMTP_PORT: "587"
      SMTP_FROM: "noreply@${DOMAIN}"
      EMAIL_API_KEY_EXPIRATION_ENABLED: "true"
      EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED: "true"
      EMAIL_ONE_TIME_ACCESS_AS_UNAUTHENTICATED_ENABLED: "false"
      EMAIL_VERIFICATION_ENABLED: "true"
