services:
  duc:
    container_name: duc
    image: ${DUC_IMAGE:-tigerdockermediocore/duc-docker}:${DUC_IMAGE_TAG:-latest}
    profiles: ["${DUC_PROFILE:-disabled}"]
    # restart: unless-stopped
    networks:
      - internal
    depends_on:
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    volumes:
      - "$PATH_MOVIES:/host/movies:ro"
      - "$PATH_MUSIC:/host/Music:ro"
      - "$PATH_TV:/host/tv:ro"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Information"
      - "homepage.name=DUC"
      - "homepage.icon=qdirstat.png"
      - "homepage.href=https://duc.$DOMAIN/"
      - "homepage.description=Disk usage analyzer"

      - "traefik.enable=true"
      - "traefik.http.routers.duc.rule=Host(`duc.$DOMAIN`)"
      - "traefik.http.routers.duc.middlewares=duc,tinyauth,error-pages"
      - "traefik.http.services.duc.loadbalancer.server.port=80"
      - "traefik.http.middlewares.duc.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.duc.headers.accessControlAllowOriginList=https://$DOMAIN"

    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "timeout 1 bash -c 'cat < /dev/null > /dev/tcp/localhost/80'"
