services:
  tracearr:
    container_name: tracearr
    image: ${TRACEARR_IMAGE:-ghcr.io/connorgallopo/tracearr}:${TRACEARR_IMAGE_TAG:-supervised}
    profiles: ["${TRACEARR_PROFILE:-quality}"]
    restart: unless-stopped
    networks:
      - internal
      - external
    depends_on:
      traefik:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      TZ: "${TZ:-Europe/London}"
      CORS_ORIGIN: "https://tracearr.${DOMAIN}"
      FORCE_DB_REINIT: "true"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/postgres:/data/postgres"
      - "./config/redis:/data/redis"
      - "./config/tracearr:/data/tracearr"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Libraries"
      - "homepage.name=Tracearr"
      - "homepage.icon=tracearr.png"
      - "homepage.href=https://tracearr.$DOMAIN/"
      - "homepage.description=Plex and Emby Monitoring"
      - "homepage.widget.type=tracearr"
      - "homepage.widget.url=http://tracearr:3000"
      - "homepage.widget.key={{HOMEPAGE_FILE_TRACEARR_API}}"
      - "homepage.widget.showEpisodeNumber=true"
      - "homepage.widget.expandOneStreamToTwoRows=false"

      - "traefik.enable=true"
      - "traefik.http.routers.tracearr.rule=Host(`tracearr.$DOMAIN`)"
      - "traefik.http.routers.tracearr.middlewares=tracearr,tinyauth,error-pages"
      - "traefik.http.services.tracearr.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.tracearr.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.tracearr.headers.accessControlAllowOriginList=https://$DOMAIN"

  homepage:
    secrets:
      - tracearr_api
    environment:
      HOMEPAGE_FILE_TRACEARR_API: "/run/secrets/tracearr_api"

secrets:
  tracearr_api:
    environment: "TRACEARR_API"
