# Add extra domains for routing and SSL certs
#############################################
# entryPoints:
#   websecure:
#     http:
#       tls:
#         domains:
#           - main: "<<domain>"
#             sans: "*.<<domain>>"

# If using cloudflare make sure we trust the source-ip
######################################################
# entryPoints:
#   websecure:
#     http:
#       middlewares:
#         - cloudflarewarp

# experimental:
#   plugins:
#     cloudflarewarp:
#       modulename: github.com/BilikoX/cloudflarewarp
#       version: v1.3.4

# http:
#   middlewares:
#     cloudflarewarp:
#       plugin:
#         cloudflarewarp:
#           disableDefault: false
#           trustip: # Trust IPS not required if disableDefault is false - we will allocate Cloud Flare IPs automatically
#             - "2400:cb00::/32"

# Routes that want to do something that doesn't involve docker
##############################################################
# http:
#   routers:
#     <<outside-docker>>: # A web server running on your local network that wants to be protected - this will not expose the url
#       rule: "Host(`<<subdomain>>.<<domain>>`)"
#       middlewares: allow-auth,tinyauth@docker,error-pages@docker
#       service: <<outside-docker>>

#     <<redirect>>: # Redirect the browser so it will navigate to the new url
#       rule: "Host(`<<subdomain>>.<<domain>>`)"
#       middlewares: <<redirect>>
#       service: noop@internal

#   middlewares:
#     allow-auth: # Allows the auth header to be forwarded (optional - needed for Cockpit)
#       headers:
#         customResponseHeaders:
#           Access-Control-Allow-Headers: authorization

#     <<redirect>>:
#       redirectRegex:
#         regex: "(.*)"
#         replacement: "<<url>>"

#   services:
#     <<outside-docker>>:
#       loadBalancer:
#         servers:
#           - url: "<<url>>"
