services:
  error-pages:
    container_name: error-pages
    image: ${ERROR_PAGES_IMAGE:-ghcr.io/tarampampam/error-pages}:${ERROR_PAGES_IMAGE_TAG:-latest}
    profiles: ["${ERROR_PAGES_PROFILE:-network}"]
    restart: unless-stopped
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Image
      TEMPLATE_NAME: "lost-in-space"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

      - "traefik.enable=true"
      - "traefik.http.services.error-pages.loadbalancer.server.port=8080"
      # use as "fallback" for any NON-registered services (with priority below normal)
      - "traefik.http.routers.error-pages.rule=Host(`error-pages.$DOMAIN`) || HostRegexp(`.+`)"
      - "traefik.http.routers.error-pages.priority=10"
      # - "traefik.http.routers.error-pages.entrypoints=web"
      - "traefik.http.routers.error-pages.middlewares=error-pages"
      # "error-pages" middleware settings
      - "traefik.http.middlewares.error-pages.errors.status=400-599"
      - "traefik.http.middlewares.error-pages.errors.service=error-pages"
      - "traefik.http.middlewares.error-pages.errors.query=/{status}.html"

# Add to others:
      # - "traefik.http.routers.external.middlewares=error-pages"
