services:
  error-pages:
    container_name: error-pages
    image: ghcr.io/tarampampam/error-pages:latest
    profiles: ["network"]
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      traefik:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Image
      TEMPLATE_NAME: "lost-in-space"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      # use as "fallback" for any NON-registered services (with priority below normal)
      - "traefik.http.routers.error-pages.priority=10"
      # - "traefik.http.routers.error-pages.entrypoints=web"
      - "traefik.http.routers.error-pages.rule=HostRegexp(`.+`)"
      - "traefik.http.routers.error-pages.middlewares=error-pages"
      - "traefik.http.services.error-pages.loadbalancer.server.port=8080"
      # "error-pagess" middleware settings
      - "traefik.http.middlewares.error-pages.errors.status=400-599"
      - "traefik.http.middlewares.error-pages.errors.service=error-pages"
      - "traefik.http.middlewares.error-pages.errors.query=/{status}.html"

# Add to others:
      # - "traefik.http.routers.external.middlewares=error-pages"
