services:
  onlyfans:
    container_name: onlyfans
    image: ghcr.io/datawhores/of-scraper:latest
    profiles: ["${PROFILE_ONLYFANS:-download}"]
    restart: unless-stopped
    networks:
      - external
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
      # Image
    stdin_open: true
    tty: true
    volumes:
        - "./config:/home/ofscraper/.config"
        - "./logs:/home/ofscraper/.config/ofscraper/logging"
        - "/usr/bin/ffmpeg:/usr/bin/ffmpeg:ro" # standalone build
        - "/usr/local/bin/mp4decrypt:/usr/local/bin/mp4decrypt:ro"
        - "$PATH_ONLYFANS:/data/Adult"
    command:
      - ofscraper
      - "--daemon"
      - "10800" # 3600 = hour, 10800 = 3 hours
      - "--posts"
      - "all"
      - "--action"
      - "download" # ,like
      - "--username"
      - "ALL"
      - "--block-ads"
      # - "--force-model-unique"
