services:
  watchtower:
    container_name: watchtower
    image: ${WATCHTOWER_IMAGE:-containrrr/watchtower}:${WATCHTOWER_IMAGE_TAG:-latest}
    profiles: ["${WATCHTOWER_PROFILE:-infrastructure}"]
    restart: unless-stopped
    networks:
      - external
      - internal
    depends_on:
      socket-proxy:
        condition: service_started
        restart: true
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Docker
      DOCKER_HOST: "tcp://socket-proxy:2375"
      # Image
      WATCHTOWER_POLL_INTERVAL: "3600"
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_TIMEOUT: "30s"
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
      - "deunhealth.restart.on.unhealthy=false"
      - "traefik.enable=false"
