services:
  watchtower:
    container_name: watchtower
    image: ${WATCHTOWER_IMAGE:-nickfedor/watchtower}:${WATCHTOWER_IMAGE_TAG:-latest}
    profiles: ["${WATCHTOWER_PROFILE:-infrastructure}"]
    restart: unless-stopped
    networks:
      - external
      - internal
    depends_on:
      socket-proxy:
        condition: service_started
        restart: true
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "${TZ:-Europe/London}"
      # Docker
      DOCKER_HOST: "tcp://socket-proxy:2375"
      # Image
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_HTTP_API_METRICS: "true"
      WATCHTOWER_HTTP_API_TOKEN: "${WATCHTOWER_HTTP_API_TOKEN:-RaNdOm_StRiNg}"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_LABEL_TAKE_PRECEDENCE: "true"
      WATCHTOWER_POLL_INTERVAL: "3600"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_TIMEOUT: "${WATCHTOWER_TIMEOUT:-30s}"
    # volumes:
    #   - "<PATH_TO_HOME_DIR>/.docker/config.json:/config.json"
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"

      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Information"
      - "homepage.name=Watchtower"
      - "homepage.icon=watchtower.png"
      - "homepage.description=Docker image updates"
      - "homepage.widget.type=watchtower"
      - "homepage.widget.url=http://watchtower:8080"
      - "homepage.widget.key=${WATCHTOWER_HTTP_API_TOKEN:-RaNdOm_StRiNg}"

      - "traefik.enable=false"
