services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    profiles: ["infrastructure"]
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - socket-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Docker
      DOCKER_HOST: "tcp://socket-proxy:2375"
      # Image
      WATCHTOWER_POLL_INTERVAL: "3600"
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_TIMEOUT: "30s"
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.monitor-only=true"
      - "deunhealth.restart.on.unhealthy=false"
