services:
  tinyauth:
    secrets:
      - tinyauth_oauth_client_secret
    environment:
      TINYAUTH_OAUTH_PROVIDERS_OAUTH_CLIENTID: "${TINYAUTH_OAUTH_CLIENT_ID:?You must set TINYAUTH_OAUTH_CLIENT_ID}"
      TINYAUTH_OAUTH_PROVIDERS_OAUTH_CLIENTSECRETFILE: "/run/secrets/tinyauth_oauth_client_secret"
      TINYAUTH_OAUTH_PROVIDERS_OAUTH_AUTHURL: "${TINYAUTH_OAUTH_AUTH_URL:?You must set TINYAUTH_OAUTH_AUTH_URL}"
      TINYAUTH_OAUTH_PROVIDERS_OAUTH_TOKENURL: "${TINYAUTH_OAUTH_TOKEN_URL:?You must set TINYAUTH_OAUTH_TOKEN_URL}"
      TINYAUTH_OAUTH_PROVIDERS_OAUTH_USERINFOURL: "${TINYAUTH_OAUTH_USERINFO_URL:?You must the TINYAUTH_OAUTH_USERINFO_URL}"
      TINYAUTH_OAUTH_PROVIDERS_OAUTH_REDIRECTURL: "${TINYAUTH_OAUTH_REDIRECT_URL:-}"
      TINYAUTH_OAUTH_PROVIDERS_OAUTH_SCOPE: "${TINYAUTH_OAUTH_REDIRECT_SCOPES:-openid email profile groups}"
      TINYAUTH_OAUTH_PROVIDERS_OAUTH_NAME: "${TINYAUTH_OAUTH_NAME:-OAuth}"
      TINYAUTH_OAUTH_PROVIDERS_OAUTH_INSECURE: "${TINYAUTH_OAUTH_INSECURE:-false}"

secrets:
  tinyauth_oauth_client_secret:
    environment: "TINYAUTH_OAUTH_CLIENT_SECRET"
