services:
  tinyauth:
    container_name: tinyauth
    image: ${TINYAUTH_IMAGE:-ghcr.io/steveiliop56/tinyauth}:${TINYAUTH_IMAGE_TAG:-v5-distroless}
    profiles: [ "${TINYAUTH_PROFILE:-core}" ]
    restart: unless-stopped
    networks:
      - external
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    secrets:
      - google_client_secret
    environment:
      # Image
      DOCKER_HOST: "tcp://socket-proxy.internal:2375"
      TINYAUTH_ANALYTICS_ENABLED: "false"
      TINYAUTH_APPURL: "https://${TINYAUTH_SUBDOMAIN:-tinyauth}.${DOMAIN}"
      TINYAUTH_AUTH_SECURECOOKIE: "true"
      TINYAUTH_AUTH_SESSIONEXPIRY: "${SESSION_EXPIRY:-86400}" # Default is 24 hours
      TINYAUTH_LOG_LEVEL: "warn"
      TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTID: "$GOOGLE_CLIENT_ID"
      TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTSECRETFILE: "/run/secrets/google_client_secret"
      TINYAUTH_OAUTH_WHITELIST: "${WHITELIST:?Set the WHITELIST to your google email address!}"
      TINYAUTH_UI_TITLE: "${DOMAIN}"
    volumes:
      - "./config:/data"
    labels:
      deunhealth.restart.on.unhealthy: "true"
      homepage.group: "Tools"
      homepage.name: "Tinyauth"
      homepage.icon: "tinyauth.png"
      homepage.href: "https://${TINYAUTH_SUBDOMAIN:-tinyauth}.${DOMAIN}"
      homepage.description: "OAuth handling"
      traefik.enable: "true"
      traefik.http.routers.tinyauth.rule: "Host(`${TINYAUTH_SUBDOMAIN:-tinyauth}.${DOMAIN}`)"
      traefik.http.services.tinyauth.loadbalancer.server.port: "3000"
      traefik.http.middlewares.tinyauth.forwardauth.address: "http://tinyauth.internal:3000/api/auth/traefik"
      traefik.http.middlewares.tinyauth.forwardauth.authResponseHeaders: "remote-user,remote-groups"
      traefik.http.middlewares.tinyauth.forwardauth.maxResponseBodySize: "32768"
      traefik.http.middlewares.tinyauth.forwardauth.trustForwardHeader: "true"

secrets:
  google_client_secret:
    environment: "GOOGLE_CLIENT_SECRET"
