services:
  tinyauth:
    container_name: tinyauth
    image: ghcr.io/steveiliop56/tinyauth:v3
    profiles: ["${PROFILE_OAUTH:-network}"]
    restart: unless-stopped
    networks:
      - external
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Image
      SECRET: "$OAUTH_SECRET"
      APP_URL: "https://tinyauth.$DOMAIN"
      GOOGLE_CLIENT_ID: "$GOOGLE_CLIENT_ID"
      GOOGLE_CLIENT_SECRET: "$GOOGLE_CLIENT_SECRET"
      OAUTH_WHITELIST: "${WHITELIST:?Set the WHITELIST to your google email address!}"
      COOKIE_SECURE: "true"
      DISABLE_CONTINUE: "true"
      APP_TITLE: "$DOMAIN"
      # SESSION_EXPIRY: "2592000" # 30 days
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tinyauth.rule=Host(`tinyauth.$DOMAIN`)"
      - "traefik.http.services.tinyauth.loadbalancer.server.port=3000"
      # - "traefik.http.middlewares.tinyauth.forwardauth.address=http://tinyauth:3000"
      - "traefik.http.middlewares.tinyauth.forwardauth.address=http://tinyauth:3000/api/auth/traefik"
      - "traefik.http.middlewares.tinyauth.forwardauth.authResponseHeaders=X-Forwarded-User"
    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "1m30s"
      test: "curl -f http://localhost:3000/api/healthcheck || exit 1"
