services:
  mylar:
    container_name: mylar
    image: lscr.io/linuxserver/mylar3:latest
    profiles: ["${PROFILE_MYLAR:-media}"]
    restart: unless-stopped
    networks:
      - external
      - internal
    depends_on:
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./logs:/config/mylar/logs"
      - "$PATH_COMICS:/data/Comics"
      - "$PATH_DOWNLOADS:/data/Downloads"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mylar.rule=Host(`mylar.$DOMAIN`)"
      - "traefik.http.routers.mylar.middlewares=mylar,tinyauth,error-pages"
      - "traefik.http.services.mylar.loadbalancer.server.port=8090"
      - "traefik.http.middlewares.mylar.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.mylar.headers.accessControlAllowOriginList=https://$DOMAIN"
