services:
  sonarr_youtubedl:
    container_name: sonarr_youtubedl
    image: ${SONARR_YOUTUBEDL_IMAGE:-whatdaybob/sonarr_youtubedl}:${SONARR_YOUTUBEDL_IMAGE_TAG:-latest}
    profiles: ["${SONARR_YOUTUBEDL_PROFILE:-disabled}"]
    # restart: unless-stopped
    networks:
      - external
      - internal
    depends_on:
      sonarr:
        condition: service_healthy
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "${TZ:-Europe/London}"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./logs:/logs"
      - "$PATH_TV:/sonarr_root"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "traefik.enable=false"
