services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    profiles: ["${PROFILE_CLOUDFLARED:-network}"]
    restart: unless-stopped
    networks:
      - external
      - internal
    command: tunnel run
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      TUNNEL_TOKEN: "${CLOUDFLARED_TOKEN:?You must disable the cloudflared service if not using it}"
      TUNNEL_LOGLEVEL: "debug"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=false"
    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: ["CMD", "cloudflared", "tunnel", "--metrics", "0.0.0.0:20241", "ready"]
