services:
  cloudflared:
    container_name: cloudflared
    image: ${CLOUDFLARED_IMAGE:-cloudflare/cloudflared}:${CLOUDFLARED_IMAGE_TAG:-latest}
    profiles: ["${CLOUDFLARED_PROFILE:-network}"]
    restart: unless-stopped
    networks:
      - external
      - internal
    command: tunnel run
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      TUNNEL_TOKEN: "${CLOUDFLARED_TOKEN:?You must disable the cloudflared service if not using it}"
      TUNNEL_LOGLEVEL: "info"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Information"
      - "homepage.name=Cloudflared"
      - "homepage.icon=cloudflare.png"
      - "homepage.href=https://dash.cloudflare.com/"
      - "homepage.description=Cloudflare Status"
      - "homepage.widget.type=cloudflared"
      - "homepage.widget.accountid=${CLOUDFLARED_ACCOUNT_ID:-}"
      - "homepage.widget.tunnelid=${CLOUDFLARED_TUNNEL_ID:-}"
      - "homepage.widget.key=${CLOUDFLARED_API:-}"

      - "traefik.enable=false"

    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: ["CMD", "cloudflared", "tunnel", "--metrics", "0.0.0.0:20241", "ready"]
