services:
  kapowarr:
    container_name: kapowarr
    image: mrcas/kapowarr:latest
    profiles: ["${PROFILE_KAPOWARR:-media}"]
    restart: unless-stopped
    networks:
      - internal
      - external
    depends_on:
      # proxy:
      #   condition: service_started
      #   restart: false
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/app/db"
      # - "./backup:/config/Backups"
      # - "./logs:/config/logs"
      - "$PATH_COMICS:/data/comics"
      - "$PATH_DOWNLOADS:/data/Downloads"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Libraries"
      - "homepage.name=Kapowarr"
      - "homepage.icon=kapowarr.png"
      - "homepage.href=https://kapowarr.$DOMAIN/"
      - "homepage.description=Comics"
      - "homepage.weight=50"

      - "traefik.enable=true"
      - "traefik.http.routers.kapowarr.rule=Host(`kapowarr.$DOMAIN`)"
      - "traefik.http.routers.kapowarr.middlewares=kapowarr,tinyauth,error-pages"
      - "traefik.http.services.kapowarr.loadbalancer.server.port=5656"
      - "traefik.http.middlewares.kapowarr.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.kapowarr.headers.accessControlAllowOriginList=https://$DOMAIN"

    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "timeout 1 bash -c 'cat < /dev/null > /dev/tcp/localhost/5656'"
