services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    profiles: ["${PROFILE_JELLYFIN:-library}"]
    restart: unless-stopped
    networks:
      - external
      - internal
    depends_on:
      cloudflared:
        condition: service_started
        restart: false
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "2"
    ports:
      - "8096:8096"
      - "8920:8920" #optional
      - "7359:7359/udp" #optional
      - "1900:1900/udp" #optional
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
      # Image
      JELLYFIN_PublishedServerUrl: "http://jellyfin.$DOMAIN"
    volumes:
      - "./config:/config"
      - "./logs:/config/logs"
      - "./tmp:/config/cache/transcodes"
      - "$PATH_MOVIES:/data/movies:ro"
      - "$PATH_MUSIC:/data/Music:ro"
      - "$PATH_TV:/data/tv:ro"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.$DOMAIN`)"
      - "traefik.http.routers.jellyfin.middlewares=tinyauth,error-pages"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "curl --connect-timeout 15 --silent --show-error --fail http://localhost:8096/health"
