services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    profiles: ["access"]
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - traefik
      - socket-proxy
      - error-pages
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      DOCKER_HOST: "tcp://socket-proxy:2375"
      DOZZLE_HOSTNAME: "${DOMAIN}"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.$DOMAIN`)"
      - "traefik.http.routers.dozzle.middlewares=oauth,error-pages"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: ["CMD", "/dozzle", "healthcheck"]
