services:
  dozzle:
    container_name: dozzle
    image: ${DOZZLE_IMAGE:-docker.io/amir20/dozzle}:${DOZZLE_IMAGE_TAG:-v10}
    profiles: [ "${DOZZLE_PROFILE:-information}" ]
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      socket-proxy:
        condition: service_healthy
        restart: false
      traefik:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      DOCKER_HOST: "tcp://socket-proxy.internal:2375"
      DOZZLE_HOSTNAME: "${DOMAIN}"
    labels:
      deunhealth.restart.on.unhealthy: "true"
      homepage.group: "Tools"
      homepage.name: "Dozzle"
      homepage.icon: "dozzle.png"
      homepage.href: "https://${DOZZLE_SUBDOMAIN:-dozzle}.${DOMAIN}/"
      homepage.description: "Docker container logs"
      traefik.enable: "true"
      traefik.http.routers.dozzle.rule: "Host(`${DOZZLE_SUBDOMAIN:-dozzle}.${DOMAIN}`)"
      traefik.http.routers.dozzle.middlewares: "dozzle,tinyauth,error-pages"
      traefik.http.services.dozzle.loadbalancer.server.port: "8080"
      traefik.http.middlewares.dozzle.headers.accessControlAllowCredentials: "true"
      traefik.http.middlewares.dozzle.headers.accessControlAllowOriginList: "https://${DOMAIN}"
    healthcheck:
      start_period: "30s"
      test: [ "CMD", "/dozzle", "healthcheck" ]
