services:
  deunhealth:
    container_name: deunhealth
    image: qmcgaw/deunhealth:latest
    profiles: ["infrastructure"]
    restart: unless-stopped
    network_mode: none
    depends_on:
      socket-proxy:
        condition: service_healthy
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "Europe/London"
      # Docker
      DOCKER_HOST: "tcp://socket-proxy:2375"
      # Image
      LOG_LEVEL: "info"
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.monitor-only=true"
      - "deunhealth.restart.on.unhealthy=false"
