services:
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    profiles: ["media"]
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      vpn:
        condition: service_started
        restart: true
      traefik:
        condition: service_started
      error-pages:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./backup:/config/log/backup"
      - "./logs:/config/log"
      - "$PATH_MOVIES:/data/movies"
      - "$PATH_TV:/data/tv"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.$DOMAIN`)"
      - "traefik.http.routers.bazarr.middlewares=oauth,error-pages"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "curl --connect-timeout 15 --silent --show-error --fail http://localhost:6767/"
