services:
  minecraft:
    container_name: minecraft
    image: ${MINECRAFT_IMAGE:-marctv/minecraft-papermc-server}:${MINECRAFT_IMAGE_TAG:-latest}
    profiles: ["${MINECRAFT_PROFILE:-games}"]
    restart: unless-stopped
    networks:
      - internal
      - external
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
    environment:
      # Default
      TZ: "${TZ:-Europe/London}"
      PUID: "$PUID"
      PGID: "$PGID"
      # Image
      MEMORYSIZE: "${MINECRAFT_MEMORYSIZE:-1G}"
      PAPERMC_FLAGS: "${MINECRAFT_PAPERMCFLAGS:-}"
      JAVAFLAGS: "${MINECRAFT_JAVAFLAGS:-}"
    depends_on:
      traefik:
        condition: service_started
        restart: false
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/data"
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"

      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Games"
      - "homepage.name=Minecraft"
      - "homepage.icon=minecraft.png"
      - "homepage.href=https://minecraft.$DOMAIN/"
      - "homepage.description=Minecraft"
      - "homepage.widget.type=minecraft"
      - "homepage.widget.url=udp://minecraft:25565"

      - "traefik.enable=true"
      - "traefik.http.routers.minecraft.rule=Host(`minecraft.$DOMAIN`)"
      - "traefik.http.routers.minecraft.middlewares=minecraft,error-pages"
      - "traefik.http.services.minecraft.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.minecraft.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.minecraft.headers.accessControlAllowOriginList=https://$DOMAIN"

    healthcheck:
      interval: "30s"
      timeout: "1s"
      retries: 3
      start_period: "5m"
      test: "timeout 1 bash -c 'cat < /dev/null > /dev/tcp/localhost/25565'"
