#!/bin/bash

# Make a list of all folders for syncthing. This includes everything, so from
# your own server you can #include it to allow every *folder* - the same effect
# as not including it unless you have a global "**" in your .stignore file.
#
# IMPORTANT: This creates a syncthing ignore file where everything is
# explicitely allowed - very useful for manually copying lines to .stignore
# when choosing what to sync, or for creating a folder and having it start to
# sync automatically (by clicking the Test button or adding unmonitored).
#
# Configuration
#
# Create a "config/.env" file, and you can set env vars (default values):
#   IGNORE_DEPTH=2              # 1 level total
#   IGNORE_FILE=.stfolders      # Not automatically shared
#   IGNORE_ROOT=/data/Music     # Path inside docker, split multiple paths with ":"
#
# Installation
#
# 1. Add a Connection - Custom Script.
# 2. Name is "Syncthing" (or something obvious).
# 3. Trigger on "Import Complete", "Rename", "* Add", and "* Delete" (this will
#    ignore any others).
# 4. Path is "/config/make_ignore.sh".
# 5. Use "Test" to manually run the script, then "Save".

source "/config/.env" || true

IGNORE_DEPTH="${IGNORE_DEPTH:-2}"
IGNORE_FILE="${IGNORE_FILE:-.stfolders}"
IGNORE_ROOT="${IGNORE_ROOT:-/data/Music}"

declare -a valid_events=("AlbumDownload" "Rename" "Test")

>&2 echo "$lidarr_eventtype"

for eventtype in "${valid_events[@]}"; do
    if [ "$eventtype" = "$lidarr_eventtype" ]; then
        for path in ${IGNORE_ROOT//:/ }; do
            TMPFILE=$(mktemp)
            trap 'rm -f $TMPFILE' EXIT

            cd "${path%/}"
            find . -maxdepth $IGNORE_DEPTH -type d | sed -e '/^.$/d' -e 's/^./!/' -e 's/$/\//' -e 's/\[/\\[/' -e 's/]/\\]/' -e 's/{/\\{/' -e 's/}/\\}/' | sort -f -V | sed "1s;^;// AUTOGENERATED - DO NOT EDIT!\n!/$IGNORE_FILE\n\n;" > $TMPFILE

            if [ ! -f "$IGNORE_FILE" ] || [ "$(stat -c %s $TMPFILE)" != "$(stat -c %s $IGNORE_FILE)" ]; then
                cp -f $TMPFILE "${path%/}/$IGNORE_FILE"
                chmod a+r "${path%/}/$IGNORE_FILE"
            fi
        done

        exit 0 # Only run once per trigger
    fi
done

echo "make_ignore.sh: Unknown event type - $lidarr_eventtype"
