services:
  ubooquity:
    container_name: ubooquity
    image: lscr.io/linuxserver/ubooquity:latest
    profiles: ["${PROFILE_UBOOQUITY:-media}"]
    restart: unless-stopped
    networks:
      - external
      - internal
    depends_on:
      traefik:
        condition: service_started
        restart: false
      error-pages:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      UMASK: "000"
      # Image
      MAXMEM: "1024"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./logs:/config/logs"
      - "$PATH_COMICS:/comics:ro"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.ubooquity.rule=Host(`ubooquity.$DOMAIN`)"
      - "traefik.http.routers.ubooquity.middlewares=ubooquity,tinyauth,error-pages"
      - "traefik.http.services.ubooquity.loadbalancer.server.port=2202"
      - "traefik.http.middlewares.ubooquity.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.ubooquity.headers.accessControlAllowOriginList=https://$DOMAIN"
    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "curl --connect-timeout 15 --silent --show-error --fail http://localhost:2202/"
