services:
  plex-find-mismatch:
    container_name: plex-find-mismatch
    image: ${PLEX_FIND_MISMATCH_IMAGE:-rycochet/plex-find-mismatch}:${PLEX_FIND_MISMATCH_IMAGE_TAG:-latest}
    profiles: ["${PLEX_FIND_MISMATCH_PROFILE:-quality}"]
    restart: unless-stopped
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    depends_on:
      plex:
        condition: service_healthy
        restart: true
    environment:
      # Default
      TZ: "${TZ:-Europe/London}"
      PUID: "$PUID"
      PGID: "$PGID"
      # Image
      PLEX_TOKEN: "$PLEX_TOKEN"
      PLEX_URL: "https://plex.$DOMAIN:443/"
      CHECK_LIBRARY: "Movies,TV Shows"
      CHECK_UNMATCH: "false"
      # CHECK_NOW: "true"
    volumes:
      - "$PATH_MOVIES:/data/movies:ro"
      - "$PATH_TV:/data/tv:ro"
    labels:
      - "deunhealth.restart.on.unhealthy=false"
      - "traefik.enable=false"
