services:
  plex-find-mismatch:
    container_name: plex-find-mismatch
    image: rycochet/plex-find-mismatch:latest
    profiles: ["${PROFILE_PLEX_FIND_MISMATCH:-quality}"]
    restart: unless-stopped
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    depends_on:
      plex:
        condition: service_healthy
        restart: true
    environment:
      # Default
      TZ: "Europe/London"
      PUID: "$PUID"
      PGID: "$PGID"
      # Image
      PLEX_TOKEN: "$PLEX_TOKEN"
      PLEX_URL: "https://plex.$DOMAIN:443/"
      CHECK_LIBRARY: "Movies,TV Shows"
      CHECK_UNMATCH: "false"
      # CHECK_NOW: "true"
    volumes:
      - "$PATH_MOVIES:/data/movies:ro"
      - "$PATH_TV:/data/tv:ro"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "deunhealth.restart.on.unhealthy=false"
      - "traefik.enable=false"
