#!/bin/bash

# Make a synclist of all files for syncthing. This allows everything, so from
# your own server you can #include it to allow every *folder* - but the first
# match is taken, so be careful about load order!

source "$(dirname $(dirname $(readlink -f "$0")))/.env"

declare -a arr=("$PATH_AUDIOBOOKS")

for i in "${arr[@]}"; do
    cd $i
    find . -maxdepth 2 -type d | sed -e '/^.$/d' -e 's/^./!/' -e 's/$/\//' -e 's/\[/\\[/' -e 's/]/\\]/' -e 's/{/\\{/' -e 's/}/\\}/' | sort -f -V | sed "1s;^;// AUTOGENERATED!\n!/.st.$DOMAIN\n\n;" > ".st.$DOMAIN"
done
