services:
  postgres:
    container_name: postgres
    image: ${POSTGRES_IMAGE:-docker.io/postgres}:${POSTGRES_IMAGE_TAG:-18-alpine}
    profiles: [ "${POSTGRES_PROFILE:-tools}" ]
    restart: unless-stopped
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    shm_size: 128mb
    user: "${PUID:-1000}:${PGID:-1000}"
    secrets:
      - postgres_password
    environment:
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres_password"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/passwd:/etc/passwd:ro"
      - "./data:/var/lib/postgresql"
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"
      deunhealth.restart.on.unhealthy: "true"
      homepage.group: "Tools"
      homepage.name: "Postgres"
      homepage.icon: "postgres.png"
      homepage.description: "Postgres"
      traefik.enable: "false"
    healthcheck:
      start_period: "30s"
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]

secrets:
  postgres_password:
    environment: "POSTGRES_PASSWORD"
